# Generated by Django 5.2.6 on 2026-01-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('governorate', models.CharField(choices=[('ramallah', 'Ramallah'), ('nablus', 'Nablus'), ('bethlehem', 'Bethlehem'), ('jenin', 'Jenin'), ('hebron', 'Hebron')], max_length=50)),
                ('land_size', models.PositiveIntegerField()),
                ('land_type', models.CharField(choices=[('agricultural', 'Agricultural'), ('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('mixed', 'Mixed Use')], max_length=50)),
                ('political_classification', models.CharField(choices=[('a', 'Area A'), ('b', 'Area B'), ('c', 'Area C')], max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
