# Generated by Django 5.2.6 on 2026-01-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Normal_User_Side', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='land_size',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
