# Generated by Django 5.2.6 on 2026-01-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Normal_User_Side', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='estimated_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
