# Generated by Django 5.2.6 on 2026-01-08 01:56

from django.db import migrations, models


def seed_intended_uses(apps, schema_editor):
    """
    Seed the IntendedUse table with the 5 predefined values.
    """
    IntendedUse = apps.get_model('Normal_User_Side', 'IntendedUse')
    
    # Define the intended use types
    intended_use_types = [
        'residential',
        'commercial',
        'agricultural',
        'industrial',
        'mixed',
    ]
    
    # Create records if they don't exist
    for use_type in intended_use_types:
        IntendedUse.objects.get_or_create(name=use_type)


def reverse_seed_intended_uses(apps, schema_editor):
    """
    Reverse operation: delete all IntendedUse records.
    """
    IntendedUse = apps.get_model('Normal_User_Side', 'IntendedUse')
    IntendedUse.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('Normal_User_Side', '0003_project_estimated_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntendedUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('agricultural', 'Agricultural'), ('industrial', 'Industrial'), ('mixed', 'Mixed')], max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Intended Use',
                'verbose_name_plural': 'Intended Uses',
                'ordering': ['name'],
            },
        ),
        # Seed IntendedUse records immediately after creating the model
        migrations.RunPython(seed_intended_uses, reverse_seed_intended_uses),
        migrations.AddField(
            model_name='project',
            name='has_electricity',
            field=models.BooleanField(default=False, help_text='Electricity available'),
        ),
        migrations.AddField(
            model_name='project',
            name='has_internet',
            field=models.BooleanField(default=False, help_text='Internet connectivity available'),
        ),
        migrations.AddField(
            model_name='project',
            name='has_paved_road',
            field=models.BooleanField(default=False, help_text='Paved road access'),
        ),
        migrations.AddField(
            model_name='project',
            name='has_sewage',
            field=models.BooleanField(default=False, help_text='Sewage system available'),
        ),
        migrations.AddField(
            model_name='project',
            name='has_water',
            field=models.BooleanField(default=False, help_text='Water supply available'),
        ),
        migrations.AddField(
            model_name='project',
            name='slope',
            field=models.CharField(blank=True, choices=[('flat', 'Flat (0-5%)'), ('mild', 'Mild (5-15%)'), ('moderate', 'Moderate (15-30%)'), ('steep', 'Steep (>30%)')], help_text='Degree of land slope', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='town',
            field=models.CharField(blank=True, choices=[('al_buwayb', 'Al-Buwayb'), ('al_fasayil', 'Al-Fasayil'), ('wadi_assamn', 'Wadi Assamn'), ('central', 'Central Bani Naim'), ('ash_shuyukh_road', 'Ash-Shuyukh Road'), ('hebron_road', 'Hebron Road'), ('eastern', 'Eastern District'), ('western', 'Western District')], help_text='Town/Area/Neighborhood within the governorate', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='intended_uses',
            field=models.ManyToManyField(blank=True, help_text='Intended use(s) for this land', related_name='projects', to='Normal_User_Side.intendeduse'),
        ),
    ]

