# Generated by Django 5.2.6 on 2026-01-08 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Normal_User_Side', '0004_intendeduse_project_has_electricity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='area',
            field=models.CharField(blank=True, help_text='Area within the town', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='neighborhood',
            field=models.CharField(blank=True, help_text='Neighborhood/District within the area', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='town',
            field=models.CharField(blank=True, choices=[('al_buwayb', 'Al-Buwayb'), ('al_fasayil', 'Al-Fasayil'), ('wadi_assamn', 'Wadi Assamn'), ('central', 'Central Bani Naim'), ('ash_shuyukh_road', 'Ash-Shuyukh Road'), ('hebron_road', 'Hebron Road'), ('eastern', 'Eastern District'), ('western', 'Western District')], help_text='Town within the governorate', max_length=50, null=True),
        ),
    ]
