# Generated by Django 5.2.6 on 2026-01-08 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Normal_User_Side', '0005_project_area_project_neighborhood_alter_project_town'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='area',
            field=models.CharField(blank=True, choices=[('aush_alhamam', 'Aush Alhamam'), ('al_buwayb_area', 'Al-Buwayb Area'), ('central_area', 'Central Area'), ('eastern_area', 'Eastern Area'), ('western_area', 'Western Area')], help_text='Area within the town', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='neighborhood',
            field=models.CharField(blank=True, choices=[('atabalea', 'Atabalea'), ('al_mansour', 'Al-Mansour'), ('al_salam', 'Al-Salam'), ('al_noor', 'Al-Noor'), ('al_rawda', 'Al-Rawda')], help_text='Neighborhood/District within the area', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='town',
            field=models.CharField(blank=True, choices=[('bani_naem', 'Bani Naem'), ('al_buwayb', 'Al-Buwayb'), ('al_fasayil', 'Al-Fasayil'), ('wadi_assamn', 'Wadi Assamn'), ('central', 'Central Bani Naim'), ('ash_shuyukh_road', 'Ash-Shuyukh Road'), ('hebron_road', 'Hebron Road'), ('eastern', 'Eastern District'), ('western', 'Western District')], help_text='Town within the governorate', max_length=50, null=True),
        ),
    ]
