# Generated by Django 5.2.6 on 2026-01-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Normal_User_Side', '0006_alter_project_area_alter_project_neighborhood_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='land_size',
        ),
        migrations.AddField(
            model_name='project',
            name='area_m2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='facility_type_ml',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='parcel_shape',
            field=models.CharField(blank=True, choices=[('SQUARE', 'Square'), ('RECTANGLE', 'Rectangle'), ('IRREGULAR', 'Irregular')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='paved_road_1',
            field=models.CharField(blank=True, choices=[('EXISTING', 'Existing'), ('PROPOSED', 'Proposed'), ('PUBLIC', 'Public'), ('FALSE', 'None')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='paved_road_2',
            field=models.CharField(blank=True, choices=[('EXISTING', 'Existing'), ('PROPOSED', 'Proposed'), ('PUBLIC', 'Public'), ('FALSE', 'None')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='paved_road_3',
            field=models.CharField(blank=True, choices=[('EXISTING', 'Existing'), ('PROPOSED', 'Proposed'), ('PUBLIC', 'Public'), ('FALSE', 'None')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='width_m',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
