# Generated by Django 5.2.6 on 2025-11-02 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users_Handling_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
