# Generated by Django 5.2.6 on 2025-11-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users_Handling_App', '0003_activationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('normal', 'Land Appraiser'), ('scientist', 'Data Scientist'), ('admin', 'Admin')], default='normal', max_length=20),
        ),
    ]
