# Generated by Django 5.2.6 on 2026-01-18 09:58

import core.mixins
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50)),
                ('name_ar', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'areas',
            },
            bases=(core.mixins.AutoCodeMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EnvironmentalFactorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50)),
                ('label', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'environmental_factor_types',
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('code',), name='uq_environmental_factor_type_code_active')],
            },
            bases=(core.mixins.AutoCodeMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FacilityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=30)),
                ('label', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'facility_types',
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('code',), name='uq_facility_type_code_active')],
            },
            bases=(core.mixins.AutoCodeMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50)),
                ('name_ar', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'governorates',
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('code',), name='uq_governorate_code_active')],
            },
            bases=(core.mixins.AutoCodeMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LandUseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=30)),
                ('label', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'land_use_types',
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('code',), name='uq_land_use_type_code_active')],
            },
            bases=(core.mixins.AutoCodeMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('version', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('model_file_path', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ml_models',
            },
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50)),
                ('name_ar', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.area')),
            ],
            options={
                'db_table': 'neighborhoods',
            },
            bases=(core.mixins.AutoCodeMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Completed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('neighborhood_no', models.CharField(max_length=50)),
                ('parcel_no', models.CharField(max_length=50)),
                ('land_type', models.CharField(choices=[('PRIVATE', 'Private'), ('COMMON_SHARE', 'Common Share'), ('PUBLIC', 'Public')], max_length=20)),
                ('political_classification', models.CharField(choices=[('AREA_A', ' A'), ('AREA_B', ' B'), ('AREA_C', ' C')], max_length=20)),
                ('slope', models.CharField(choices=[('FLAT', 'Flat'), ('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('STEEP', 'Steep')], max_length=20)),
                ('view_quality', models.CharField(choices=[('BAD', 'Bad'), ('GOOD', 'Good'), ('FANTASTIC', 'Fantastic')], max_length=20)),
                ('area_m2', models.DecimalField(decimal_places=2, max_digits=12)),
                ('parcel_shape', models.CharField(choices=[('SQUARE', 'Square'), ('RECTANGLE', 'Rectangle'), ('TRIANGLE', 'Triangle'), ('IRREGULAR', 'Irregular')], max_length=20)),
                ('electricity', models.CharField(choices=[('YES_3PHASE', 'Yes 3-Phase'), ('YES_1PHASE', 'Yes 1-Phase'), ('NO', 'No')], max_length=20)),
                ('water', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=10)),
                ('sewage', models.CharField(choices=[('YES_PRIVATE', 'Yes Private'), ('YES_PUBLIC', 'Yes Public'), ('NO', 'No')], max_length=20)),
                ('ownership_document_type', models.CharField(choices=[('TABU', 'Tabu'), ('FINAL_SETTLEMENT', 'Final Settlement'), ('ONGOING_SETTLEMENT', 'Ongoing Settlement'), ('DURABLE_POA', 'Durable POA'), ('SALE_CONTRACT', 'Sale Contract'), ('HUJJA', 'Hujja'), ('GIFT', 'Gift')], max_length=30)),
                ('actual_price_per_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estimated_price', models.FloatField(blank=True, help_text='Generated by ML model', null=True)),
                ('land_use_residential', models.BooleanField(default=False)),
                ('land_use_commercial', models.BooleanField(default=False)),
                ('land_use_agricultural', models.BooleanField(default=False)),
                ('land_use_industrial', models.BooleanField(default=False)),
                ('hospitals_facility', models.BooleanField(default=False)),
                ('schools_facility', models.BooleanField(default=False)),
                ('police_facility', models.BooleanField(default=False)),
                ('municipality_facility', models.BooleanField(default=False)),
                ('FACTORIES_NEARBY', models.BooleanField(default=False)),
                ('NOISY_FACILITIES', models.BooleanField(default=False)),
                ('ANIMAL_FARMS', models.BooleanField(default=False)),
                ('parcel_frontage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.area')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to=settings.AUTH_USER_MODEL)),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.governorate')),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.neighborhood')),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectRoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road_status', models.CharField(choices=[('PUBLIC_EXISTING_UNPAVED', 'Public Existing Unpaved'), ('PUBLIC_EXISTING_PAVED', 'Public Existing Paved'), ('PRIVATE_EXISTING_UNPAVED', 'Private Existing Unpaved'), ('PRIVATE_EXISTING_PAVED', 'Private Existing Paved'), ('PRIVATE_PROPOSED_UNPAVED', 'Private Proposed Unpaved'), ('PUBLIC_PROPOSED_UNPAVED', 'Public Proposed Unpaved'), ('FALSE', 'No Road')], max_length=50)),
                ('road_ownership', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], max_length=20)),
                ('is_paved', models.BooleanField(default=False)),
                ('width_m', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.project')),
            ],
            options={
                'db_table': 'project_roads',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_ml_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.mlmodel')),
            ],
            options={
                'db_table': 'settings',
            },
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50)),
                ('name_ar', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.governorate')),
            ],
            options={
                'db_table': 'towns',
            },
            bases=(core.mixins.AutoCodeMixin, models.Model),
        ),
        migrations.AddField(
            model_name='project',
            name='town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.town'),
        ),
        migrations.AddField(
            model_name='area',
            name='town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.town'),
        ),
        migrations.CreateModel(
            name='Valuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_price_per_m2', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.mlmodel')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.project')),
            ],
            options={
                'db_table': 'valuations',
            },
        ),
        migrations.AddConstraint(
            model_name='neighborhood',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('area', 'code'), name='uq_neighborhood_area_code_active'),
        ),
        migrations.AddConstraint(
            model_name='town',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('governorate', 'code'), name='uq_town_governorate_code_active'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('neighborhood', 'neighborhood_no', 'parcel_no'), name='uq_project_neighborhood_parcel_active'),
        ),
        migrations.AddConstraint(
            model_name='area',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('town', 'code'), name='uq_area_town_code_active'),
        ),
        migrations.AddConstraint(
            model_name='valuation',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('project',), name='uq_valuation_project_active'),
        ),
    ]
