# Generated by Django 5.2.6 on 2026-01-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='estimated_price',
            field=models.FloatField(blank=True, help_text='Generated by ML model', null=True),
        ),
    ]
