# Generated by Django 5.2.6 on 2026-01-19 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='projectroad',
            name='road_status',
            field=models.CharField(choices=[('PUBLIC_EXISTING_UNPAVED', 'Public Existing Unpaved'), ('PUBLIC_EXISTING_PAVED', 'Public Existing Paved'), ('PRIVATE_EXISTING_UNPAVED', 'Private Existing Unpaved'), ('PRIVATE_EXISTING_PAVED', 'Private Existing Paved'), ('PRIVATE_PROPOSED_UNPAVED', 'Private Proposed Unpaved'), ('PUBLIC_PROPOSED_UNPAVED', 'Public Proposed Unpaved')], max_length=50),
        ),
    ]
