# Generated by Django 5.2.6 on 2026-01-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_code_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='actual_price_per_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
