# Generated by Django 5.2.6 on 2026-01-14 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_estimated_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='political_classification',
            field=models.CharField(choices=[('AREA_A', ' A'), ('AREA_B', ' B'), ('AREA_C', ' C')], max_length=20),
        ),
    ]
