# Generated by Django 5.2.6 on 2026-01-19 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_neighborhood_number_alter_projectroad_road_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuation',
            name='user_expected_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Appraiser's expected price as feedback for ML model", max_digits=12, null=True),
        ),
    ]
