# Generated by Django 5.2.6 on 2026-01-15 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_project_political_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlanduse',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='land_uses', to='core.project'),
        ),
    ]
