# Generated by Django 5.2.6 on 2026-01-15 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_projectlanduse_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlanduse',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.project'),
        ),
    ]
