# Generated by Django 5.2.6 on 2026-01-15 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_projectlanduse_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='price_feedback',
            field=models.TextField(blank=True, help_text='User feedback when price is rejected', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='price_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', help_text='User acceptance status of the estimated price', max_length=20),
        ),
    ]
