# Generated by Django 5.2.6 on 2026-01-15 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_project_price_feedback_project_price_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='price_feedback',
        ),
        migrations.RemoveField(
            model_name='project',
            name='price_status',
        ),
    ]
