# Generated by Django 5.2.6 on 2026-01-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_project_price_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectroad',
            name='is_paved',
            field=models.BooleanField(default=False),
        ),
    ]
